-- Neovim --
require('config.neovim.options')
require('config.neovim.keymaps')
require('config.neovim.autocommands')
require('config.neovim.colorscheme')

-- Plugins -- 
require('config.packer.plugins')
require('config.nvim-tree')
require('config.telescope')
require('config.treesitter')
require('config.mason')
require('config.cmp')
require('config.comment')
require('config.bufferline')
require('config.autopairs')
require('config.lualine')
require('config.indentline')
require('config.colorizer')
require('config.vgit')
